export const HTTP_STATUS_CODES = {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    CONFLICT: 409,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504
} as const;

export type HttpStatusCode = typeof HTTP_STATUS_CODES[keyof typeof HTTP_STATUS_CODES];

export const SERVER_ERROR_CODES: number[] = [
    HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR,
    HTTP_STATUS_CODES.BAD_GATEWAY,
    HTTP_STATUS_CODES.SERVICE_UNAVAILABLE,
    HTTP_STATUS_CODES.GATEWAY_TIMEOUT
];

export const CLIENT_ERROR_CODES: number[] = [
    HTTP_STATUS_CODES.BAD_REQUEST,
    HTTP_STATUS_CODES.FORBIDDEN,
    HTTP_STATUS_CODES.METHOD_NOT_ALLOWED,
    HTTP_STATUS_CODES.CONFLICT
];

export const AUTHORIZATION_ERROR_CODES: number[] = [
    HTTP_STATUS_CODES.UNAUTHORIZED,
    HTTP_STATUS_CODES.FORBIDDEN
];